services:
  nginx-server:
    image: ${DOCKER_USERNAME}/${DOCKER_IMAGE}:${DOCKER_TAG}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    restart: always
