---
nginx_html_dir: /var/www/html
nginx_conf_path: /etc/nginx/nginx.conf
nginx_server_name: localhost
nginx_port: 80
nginx_worker_processes: auto
nginx_worker_connections: 1024
nginx_keepalive_timeout: 65
nginx_client_max_body_size: 10M
